### ISSUE TITLE
build with qt5.15.2 ,the AppImage can sucessfully created ,when run throw exception.

### ISSUE THREAD

**Issue by xiaoyifang** [linuxdeploy/linuxdeploy#197]
/tmp/.mount_5.15.2JnvWTD/AppRun.wrapped: symbol lookup error: /lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_uri_ref

I believed that when built 2 weeks ago ,   it can work.

pls,  built with ubuntu 20.04 ,run on ubuntu 21.10 .

**Comment by TheAssassin** [comment]
I highly doubt that it worked then. But it should work now, since I rebuilt the binaries on the release page. Please try again.

Also, next time, please provide more information.

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/releases/download/v22.2.alpha-61fb1020/5.15.2-GoldenDict-61fb1020-x86_64.AppImage

this appimage built on ubuntu 20.04 can not run on ubuntu 21.

early built appimage is ok.
https://github.com/xiaoyifang/goldendict/releases/download/v22.2.alpha-f146177/GoldenDict-f146177-x86_64.AppImage

**Comment by TheAssassin** [comment]
"Can not run" is not an error description.

**Comment by xiaoyifang** [comment]
still the same error 
the latest build appimage can be found here 
https://github.com/xiaoyifang/goldendict/releases/download/v22.2.alpha-99077318/5.15.2-GoldenDict-99077318-x86_64.AppImage
```
/tmp/.mount_5.15.2GGavy3/AppRun.wrapped: symbol lookup error: /lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_uri_ref

```

**Comment by xiaoyifang** [comment]
fixed by manually  copy the missing lib into the appdir .
